name: Test and Deploy #Workflow name
on: push #what action to run the worflow [] for multiple
jobs: 
  test: #user set name of job
    runs-on: ubuntu-latest #runner used for this job
    steps: #what to run and when
      - name: Get Code 
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run Lint
        run: npm run lint
      - name: Run test
        run: npm run test
      - name: Run build
        run: npm run build